---
- hosts: all
  remote_user: devops
  tasks:
  - name: create repo
    copy:
     src: /home/student/playbook/a.repo
     dest: /etc/yum.repos.d/

- hosts: all
  remote_user: devops
  tasks:
  - name: ensure apache is at the latest version
    yum:
     name: httpd
     state: latest

- hosts: all
  remote_user: devops
  tasks:
  - name: copy html index file
    copy:
     src: /home/student/playbook/abc.html
     dest: /var/www/html/index.html
     owner: apache

- hosts: all
  remote_user: devops
  tasks:
  - name : start service httpd
    service:
     name: httpd
     state: started
     enabled: yes

- hosts: all
  remote_user: devops
  tasks:
  - name: use firewall
    firewalld:
     service: http
     permanent: yes
     immediate: yes
     state: enabled

- hosts: all
  remote_user: devops
  tasks:
  - name: restart apache
    service: 
      name: httpd
      state: restarted
